mixin () {
  public query func getApiDoc() : async Text {
    "# NOVA Backend API\n"
    # "\n"
    # "NOVA (Plan. Collaborate. Deliver.) is a project-management application. This\n"
    # "backend canister exposes a Candid API for authentication, projects, tasks,\n"
    # "comments, activity logging, and OQL data querying.\n"
    # "\n"
    # "## Authentication & Authorization\n"
    # "\n"
    # "Access is gated by a role-based access-control system. Roles are `#admin`,\n"
    # "`#user`, and `#guest`. Anonymous callers resolve to `#guest`.\n"
    # "\n"
    # "### Registration\n"
    # "\n"
    # "A caller must register before using role-guarded endpoints. Registration happens\n"
    # "when a caller signs in through the app's own frontend (which calls\n"
    # "`_internet_identity_sign_in_start` then `_internet_identity_sign_in_finish`), or\n"
    # "by calling `_initialize_access_control` once as a signed-in caller. The first\n"
    # "principal to register becomes the `#admin`; every subsequent caller becomes a\n"
    # "`#user`. A caller can be unregistered while the app already knows it, because\n"
    # "registration happens only when a caller signs in through the app's own frontend:\n"
    # "a principal that never did so is unregistered even when it belongs to the app's\n"
    # "owner, and a signed-in caller derived against a different origin is a different\n"
    # "principal than the one the frontend registered.\n"
    # "\n"
    # "### Identity derivation\n"
    # "\n"
    # "The frontend pins an Internet Identity derivation origin, published at\n"
    # "`/.well-known/ii-derivation-origin` when available. An agent already holding the\n"
    # "user's Internet Identity authorization derives the correct per-app principal\n"
    # "against that origin (for example `icp identity link web <name> --app <host>`).\n"
    # "Such a delegation acts with the user's full authority in this app until it\n"
    # "expires.\n"
    # "\n"
    # "### Role-guarded behavior\n"
    # "\n"
    # "- `getCallerUserRole()` — returns the caller's role. An anonymous caller gets\n"
    # "  `#guest`; a signed-in but unregistered caller traps with\n"
    # "  User is not registered.\n"
    # "- `isCallerAdmin()` — returns whether the caller is the `#admin`.\n"
    # "- `assignCallerUserRole(user, role)` — requires the caller to be `#admin`;\n"
    # "  otherwise it traps with Unauthorized: Only admins can assign user roles.\n"
    # "- `createProject(name, description)` — requires a registered `#user` (or\n"
    # "  `#admin`); otherwise it traps with\n"
    # "  Unauthorized: Only registered users can create projects.\n"
    # "- Task operations (`createTask`, `getTask`, `listTasks`, `updateTask`,\n"
    # "  `deleteTask`, `setTaskStatus`, `setTaskAssignee`, `addComment`,\n"
    # "  `listComments`, `listActivity`) — require a registered `#user`; otherwise they\n"
    # "  trap with Unauthorized: Only users can perform this action.\n"
    # "\n"
    # "## Projects\n"
    # "\n"
    # "- `createProject(name, description)` — creates a project owned by the caller as\n"
    # "  its Admin. Returns `Result<Project, ProjectError>`.\n"
    # "- `getProject(projectId)` — returns the project if the caller is a member,\n"
    # "  otherwise `null`.\n"
    # "- `listMyProjects()` — lists every project the caller belongs to (owner or\n"
    # "  member).\n"
    # "- `updateProject(projectId, name, description, status)` — Admin owner only.\n"
    # "- `deleteProject(projectId)` — Admin owner only.\n"
    # "- `addMember(projectId, user)` / `removeMember(projectId, user)` — Admin owner\n"
    # "  only.\n"
    # "- `getDashboard()` — aggregates project and task counts for the caller's\n"
    # "  projects.\n"
    # "\n"
    # "## Tasks\n"
    # "\n"
    # "- `createTask(projectId, title, description, priority, assignee, dueDate)` —\n"
    # "  creates a task in a project.\n"
    # "- `getTask(taskId)` — returns the task, or `null`.\n"
    # "- `listTasks(projectId)` — lists tasks in a project.\n"
    # "- `updateTask(taskId, title, description, priority, dueDate)` — project owner or\n"
    # "  task assignee only.\n"
    # "- `deleteTask(taskId)` — project Admin owner only.\n"
    # "- `setTaskStatus(taskId, status)` — project owner or assignee only.\n"
    # "- `setTaskAssignee(taskId, assignee)` — project owner or assignee only.\n"
    # "- `addComment(taskId, body)` — adds a comment to a task.\n"
    # "- `listComments(taskId)` — lists a task's comments.\n"
    # "- `listActivity(projectId)` — lists a project's activity log, newest first.\n"
    # "\n"
    # "## OQL\n"
    # "\n"
    # "- `schema()` — returns the JSON schema of the queryable entities.\n"
    # "- `execute(qJson)` — runs a JSON query and returns a typed Candid result.\n"
    # "\n"
    # "The queryable entities are `project`, `task`, `comment`, and `activity`. Each is\n"
    # "exposed `.controllerOnly()`: end users cannot read them directly, but the\n"
    # "platform's Data Intelligence agent (which calls as the controller) can answer\n"
    # "questions over them.\n"
    # "\n"
    # "## Units & Encodings\n"
    # "\n"
    # "- Timestamps (`createdAt`, `updatedAt`, `joinedAt`, `dueDate`) are `Int`\n"
    # "  nanoseconds since the Unix epoch.\n"
    # "- `Principal` values are Candid principals.\n"
    # "- Optional fields (`assignee`, `dueDate`) use `null` for none.\n"
    # "- `ProjectStatus` is `#active` / `#completed` / `#archived`.\n"
    # "- `TaskStatus` is `#todo` / `#inProgress` / `#done`.\n"
    # "- `TaskPriority` is `#low` / `#medium` / `#high`.\n"
    # "- `ProjectRole` is `#admin` / `#member`.\n"
    # "\n"
    # "## Lifecycle & Polling\n"
    # "\n"
    # "- Projects and tasks are created, updated, and deleted through explicit update\n"
    # "  calls. There are no background jobs or long-running operations to poll.\n"
    # "- `getTask` / `getProject` return `null` when the resource does not exist; a\n"
    # "  caller can poll these to observe creation or deletion.\n"
    # "\n"
    # "## Mutation Retry Safety\n"
    # "\n"
    # "- Update calls are idempotent in effect: re-applying the same update overwrites\n"
    # "  the same record. There is no separate create-or-fail guard, so a retried\n"
    # "  `createProject` / `createTask` creates a new record with a new id each time.\n"
    # "- `addMember` returns `#alreadyMember` if the user is already on the team;\n"
    # "  `removeMember` returns `#notMember` if the user is not on the team.\n"
    # "- Deleting a task also removes its comments.\n"
    # "\n"
    # "## Errors\n"
    # "\n"
    # "- Project operations return `Result<_, ProjectError>` with variants `#notFound`,\n"
    # "  `#notAuthorized`, `#notMember`, `#alreadyMember`, and `#invalidName`.\n"
    # "- Authorization failures on task and project endpoints trap (reject) rather\n"
    # "  than returning a `Result`; the trap message is quoted above.\n"
    # "- `getCallerUserRole` traps with User is not registered for a signed-in but\n"
    # "  unregistered caller.\n"
    # "\n"
    # "## Non-obvious gotchas\n"
    # "\n"
    # "- `execute` is named so because `query` is a reserved keyword in Motoko.\n"
    # "- The OQL entities are `.controllerOnly()`: a signed-in end user calling\n"
    # "  `schema()` / `execute()` sees no entities, while the controller sees all.\n"
    # "- `getDashboard` currently reports zero task counts and zero progress until the\n"
    # "  tasks domain is fully wired into the aggregation.\n"
  };
};
