/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent {
  'id' : bigint,
  'action' : string,
  'createdAt' : bigint,
  'projectId' : bigint,
  'actorPrincipal' : Principal,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Comment {
  'id' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'author' : Principal,
  'taskId' : bigint,
}
export interface DashboardSummary {
  'overdueTasks' : bigint,
  'taskCounts' : TaskStatusCounts,
  'totalProjects' : bigint,
  'progress' : Array<ProjectProgress>,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'members' : Array<ProjectMember>,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export type ProjectError = { 'notAuthorized' : null } |
  { 'notMember' : null } |
  { 'alreadyMember' : null } |
  { 'notFound' : bigint } |
  { 'invalidName' : null };
export interface ProjectMember {
  'joinedAt' : bigint,
  'role' : ProjectRole,
  'user' : Principal,
}
export interface ProjectProgress {
  'status' : ProjectStatus,
  'doneTasks' : bigint,
  'totalTasks' : bigint,
  'name' : string,
  'projectId' : bigint,
  'percentDone' : bigint,
}
export type ProjectRole = { 'member' : null } |
  { 'admin' : null };
export type ProjectStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'archived' : null };
export type Result = { 'ok' : Project } |
  { 'err' : ProjectError };
export type Result_1 = { 'ok' : null } |
  { 'err' : ProjectError };
export type Result_2 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'assignee' : [] | [Principal],
  'title' : string,
  'createdAt' : bigint,
  'dueDate' : [] | [bigint],
  'description' : string,
  'updatedAt' : bigint,
  'projectId' : bigint,
  'priority' : TaskPriority,
}
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TaskStatus = { 'done' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export interface TaskStatusCounts {
  'done' : bigint,
  'todo' : bigint,
  'inProgress' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_2>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addComment' : ActorMethod<[bigint, string], Comment>,
  'addMember' : ActorMethod<[bigint, Principal], Result_1>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string, string], Result>,
  'createTask' : ActorMethod<
    [bigint, string, string, TaskPriority, [] | [Principal], [] | [bigint]],
    Task
  >,
  'deleteProject' : ActorMethod<[bigint], Result_1>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result__1>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboard' : ActorMethod<[], DashboardSummary>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivity' : ActorMethod<[bigint], Array<ActivityEvent>>,
  'listComments' : ActorMethod<[bigint], Array<Comment>>,
  'listMyProjects' : ActorMethod<[], Array<Project>>,
  'listTasks' : ActorMethod<[bigint], Array<Task>>,
  'removeMember' : ActorMethod<[bigint, Principal], Result_1>,
  'schema' : ActorMethod<[], string>,
  'setTaskAssignee' : ActorMethod<[bigint, [] | [Principal]], Task>,
  'setTaskStatus' : ActorMethod<[bigint, TaskStatus], Task>,
  'updateProject' : ActorMethod<
    [bigint, string, string, ProjectStatus],
    Result
  >,
  'updateTask' : ActorMethod<
    [bigint, string, string, TaskPriority, [] | [bigint]],
    Task
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];