/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'author' : IDL.Principal,
  'taskId' : IDL.Nat,
});
export const ProjectError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notMember' : IDL.Null,
  'alreadyMember' : IDL.Null,
  'notFound' : IDL.Nat,
  'invalidName' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ProjectError });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'archived' : IDL.Null,
});
export const ProjectRole = IDL.Variant({
  'member' : IDL.Null,
  'admin' : IDL.Null,
});
export const ProjectMember = IDL.Record({
  'joinedAt' : IDL.Int,
  'role' : ProjectRole,
  'user' : IDL.Principal,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'members' : IDL.Vec(ProjectMember),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : Project, 'err' : ProjectError });
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'done' : IDL.Null,
  'todo' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'assignee' : IDL.Opt(IDL.Principal),
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'projectId' : IDL.Nat,
  'priority' : TaskPriority,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const TaskStatusCounts = IDL.Record({
  'done' : IDL.Nat,
  'todo' : IDL.Nat,
  'inProgress' : IDL.Nat,
});
export const ProjectProgress = IDL.Record({
  'status' : ProjectStatus,
  'doneTasks' : IDL.Nat,
  'totalTasks' : IDL.Nat,
  'name' : IDL.Text,
  'projectId' : IDL.Nat,
  'percentDone' : IDL.Nat,
});
export const DashboardSummary = IDL.Record({
  'overdueTasks' : IDL.Nat,
  'taskCounts' : TaskStatusCounts,
  'totalProjects' : IDL.Nat,
  'progress' : IDL.Vec(ProjectProgress),
});
export const ActivityEvent = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'createdAt' : IDL.Int,
  'projectId' : IDL.Nat,
  'actorPrincipal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [Comment], []),
  'addMember' : IDL.Func([IDL.Nat, IDL.Principal], [Result_1], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'createTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        TaskPriority,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Int),
      ],
      [Task],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Nat], [Result_1], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func([], [DashboardSummary], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivity' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityEvent)], ['query']),
  'listComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'listMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'removeMember' : IDL.Func([IDL.Nat, IDL.Principal], [Result_1], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setTaskAssignee' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Principal)], [Task], []),
  'setTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [Task], []),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, ProjectStatus],
      [Result],
      [],
    ),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, TaskPriority, IDL.Opt(IDL.Int)],
      [Task],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'author' : IDL.Principal,
    'taskId' : IDL.Nat,
  });
  const ProjectError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notMember' : IDL.Null,
    'alreadyMember' : IDL.Null,
    'notFound' : IDL.Nat,
    'invalidName' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ProjectError });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'archived' : IDL.Null,
  });
  const ProjectRole = IDL.Variant({ 'member' : IDL.Null, 'admin' : IDL.Null });
  const ProjectMember = IDL.Record({
    'joinedAt' : IDL.Int,
    'role' : ProjectRole,
    'user' : IDL.Principal,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'members' : IDL.Vec(ProjectMember),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : Project, 'err' : ProjectError });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'done' : IDL.Null,
    'todo' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'assignee' : IDL.Opt(IDL.Principal),
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'projectId' : IDL.Nat,
    'priority' : TaskPriority,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const TaskStatusCounts = IDL.Record({
    'done' : IDL.Nat,
    'todo' : IDL.Nat,
    'inProgress' : IDL.Nat,
  });
  const ProjectProgress = IDL.Record({
    'status' : ProjectStatus,
    'doneTasks' : IDL.Nat,
    'totalTasks' : IDL.Nat,
    'name' : IDL.Text,
    'projectId' : IDL.Nat,
    'percentDone' : IDL.Nat,
  });
  const DashboardSummary = IDL.Record({
    'overdueTasks' : IDL.Nat,
    'taskCounts' : TaskStatusCounts,
    'totalProjects' : IDL.Nat,
    'progress' : IDL.Vec(ProjectProgress),
  });
  const ActivityEvent = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'createdAt' : IDL.Int,
    'projectId' : IDL.Nat,
    'actorPrincipal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [Comment], []),
    'addMember' : IDL.Func([IDL.Nat, IDL.Principal], [Result_1], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'createTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          TaskPriority,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Int),
        ],
        [Task],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Nat], [Result_1], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func([], [DashboardSummary], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivity' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityEvent)], ['query']),
    'listComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'listMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'removeMember' : IDL.Func([IDL.Nat, IDL.Principal], [Result_1], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setTaskAssignee' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Principal)], [Task], []),
    'setTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [Task], []),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, ProjectStatus],
        [Result],
        [],
      ),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, TaskPriority, IDL.Opt(IDL.Int)],
        [Task],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };