/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Result_2 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ProjectMember {
    joinedAt: bigint;
    role: ProjectRole;
    user: Principal;
}
export interface ProjectProgress {
    status: ProjectStatus;
    doneTasks: bigint;
    totalTasks: bigint;
    name: string;
    projectId: bigint;
    percentDone: bigint;
}
export interface Comment {
    id: bigint;
    body: string;
    createdAt: bigint;
    author: Principal;
    taskId: bigint;
}
export type ProjectError = {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notMember";
    notMember: null;
} | {
    __kind__: "alreadyMember";
    alreadyMember: null;
} | {
    __kind__: "notFound";
    notFound: bigint;
} | {
    __kind__: "invalidName";
    invalidName: null;
};
export interface Task {
    id: bigint;
    status: TaskStatus;
    assignee?: Principal;
    title: string;
    createdAt: bigint;
    dueDate?: bigint;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
    priority: TaskPriority;
}
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface DashboardSummary {
    overdueTasks: bigint;
    taskCounts: TaskStatusCounts;
    totalProjects: bigint;
    progress: Array<ProjectProgress>;
}
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: ProjectError;
};
export type Result = {
    __kind__: "ok";
    ok: Project;
} | {
    __kind__: "err";
    err: ProjectError;
};
export interface ActivityEvent {
    id: bigint;
    action: string;
    createdAt: bigint;
    projectId: bigint;
    actorPrincipal: Principal;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface TaskStatusCounts {
    done: bigint;
    todo: bigint;
    inProgress: bigint;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface Project {
    id: bigint;
    status: ProjectStatus;
    members: Array<ProjectMember>;
    owner: Principal;
    name: string;
    createdAt: bigint;
    description: string;
}
export enum ProjectRole {
    member = "member",
    admin = "admin"
}
export enum ProjectStatus {
    active = "active",
    completed = "completed",
    archived = "archived"
}
export enum TaskPriority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum TaskStatus {
    done = "done",
    todo = "todo",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_2>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addComment(taskId: bigint, body: string): Promise<Comment>;
    addMember(projectId: bigint, user: Principal): Promise<Result_1>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProject(name: string, description: string): Promise<Result>;
    createTask(projectId: bigint, title: string, description: string, priority: TaskPriority, assignee: Principal | null, dueDate: bigint | null): Promise<Task>;
    deleteProject(projectId: bigint): Promise<Result_1>;
    deleteTask(taskId: bigint): Promise<void>;
    execute(qJson: string): Promise<Result__1>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboard(): Promise<DashboardSummary>;
    getProject(projectId: bigint): Promise<Project | null>;
    getTask(taskId: bigint): Promise<Task | null>;
    isCallerAdmin(): Promise<boolean>;
    listActivity(projectId: bigint): Promise<Array<ActivityEvent>>;
    listComments(taskId: bigint): Promise<Array<Comment>>;
    listMyProjects(): Promise<Array<Project>>;
    listTasks(projectId: bigint): Promise<Array<Task>>;
    removeMember(projectId: bigint, user: Principal): Promise<Result_1>;
    schema(): Promise<string>;
    setTaskAssignee(taskId: bigint, assignee: Principal | null): Promise<Task>;
    setTaskStatus(taskId: bigint, status: TaskStatus): Promise<Task>;
    updateProject(projectId: bigint, name: string, description: string, status: ProjectStatus): Promise<Result>;
    updateTask(taskId: bigint, title: string, description: string, priority: TaskPriority, dueDate: bigint | null): Promise<Task>;
}
import type { Cell as _Cell, DashboardSummary as _DashboardSummary, Error as _Error, Project as _Project, ProjectError as _ProjectError, ProjectMember as _ProjectMember, ProjectProgress as _ProjectProgress, ProjectRole as _ProjectRole, ProjectStatus as _ProjectStatus, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result__1 as _Result__1, Task as _Task, TaskPriority as _TaskPriority, TaskStatus as _TaskStatus, TaskStatusCounts as _TaskStatusCounts, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addMember(arg0: bigint, arg1: Principal): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(arg0, arg1);
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(arg0, arg1);
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: bigint, arg1: string, arg2: string, arg3: TaskPriority, arg4: Principal | null, arg5: bigint | null): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_TaskPriority_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_TaskPriority_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return from_candid_DashboardSummary_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return from_candid_DashboardSummary_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActivity(arg0: bigint): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivity(arg0);
            return result;
        }
    }
    async listComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComments(arg0);
            return result;
        }
    }
    async listMyProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyProjects();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyProjects();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasks(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasks(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasks(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeMember(arg0: bigint, arg1: Principal): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0, arg1);
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0, arg1);
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setTaskAssignee(arg0: bigint, arg1: Principal | null): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.setTaskAssignee(arg0, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTaskAssignee(arg0, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async setTaskStatus(arg0: bigint, arg1: TaskStatus): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.setTaskStatus(arg0, to_candid_TaskStatus_n53(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTaskStatus(arg0, to_candid_TaskStatus_n53(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: string, arg3: ProjectStatus): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2, to_candid_ProjectStatus_n55(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2, to_candid_ProjectStatus_n55(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: TaskPriority, arg4: bigint | null): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_TaskPriority_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_TaskPriority_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cell_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardSummary_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardSummary): DashboardSummary {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectError_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectError): ProjectError {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectMember_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectMember): ProjectMember {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectProgress_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectProgress): ProjectProgress {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectRole): ProjectRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    members: Array<_ProjectMember>;
    owner: Principal;
    name: string;
    createdAt: bigint;
    description: string;
}): {
    id: bigint;
    status: ProjectStatus;
    members: Array<ProjectMember>;
    owner: Principal;
    name: string;
    createdAt: bigint;
    description: string;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n15(_uploadFile, _downloadFile, value.status),
        members: from_candid_vec_n17(_uploadFile, _downloadFile, value.members),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    joinedAt: bigint;
    role: _ProjectRole;
    user: Principal;
}): {
    joinedAt: bigint;
    role: ProjectRole;
    user: Principal;
} {
    return {
        joinedAt: value.joinedAt,
        role: from_candid_ProjectRole_n20(_uploadFile, _downloadFile, value.role),
        user: value.user
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    assignee: [] | [Principal];
    title: string;
    createdAt: bigint;
    dueDate: [] | [bigint];
    description: string;
    updatedAt: bigint;
    projectId: bigint;
    priority: _TaskPriority;
}): {
    id: bigint;
    status: TaskStatus;
    assignee?: Principal;
    title: string;
    createdAt: bigint;
    dueDate?: bigint;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
    priority: TaskPriority;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n28(_uploadFile, _downloadFile, value.status),
        assignee: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.assignee)),
        title: value.title,
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        updatedAt: value.updatedAt,
        projectId: value.projectId,
        priority: from_candid_TaskPriority_n32(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n36(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n40(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    overdueTasks: bigint;
    taskCounts: _TaskStatusCounts;
    totalProjects: bigint;
    progress: Array<_ProjectProgress>;
}): {
    overdueTasks: bigint;
    taskCounts: TaskStatusCounts;
    totalProjects: bigint;
    progress: Array<ProjectProgress>;
} {
    return {
        overdueTasks: value.overdueTasks,
        taskCounts: value.taskCounts,
        totalProjects: value.totalProjects,
        progress: from_candid_vec_n46(_uploadFile, _downloadFile, value.progress)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ProjectStatus;
    doneTasks: bigint;
    totalTasks: bigint;
    name: string;
    projectId: bigint;
    percentDone: bigint;
}): {
    status: ProjectStatus;
    doneTasks: bigint;
    totalTasks: bigint;
    name: string;
    projectId: bigint;
    percentDone: bigint;
} {
    return {
        status: from_candid_ProjectStatus_n15(_uploadFile, _downloadFile, value.status),
        doneTasks: value.doneTasks,
        totalTasks: value.totalTasks,
        name: value.name,
        projectId: value.projectId,
        percentDone: value.percentDone
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Project;
} | {
    err: _ProjectError;
}): {
    __kind__: "ok";
    ok: Project;
} | {
    __kind__: "err";
    err: ProjectError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Project_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ProjectError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    archived: null;
}): ProjectStatus {
    return "active" in value ? ProjectStatus.active : "completed" in value ? ProjectStatus.completed : "archived" in value ? ProjectStatus.archived : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    admin: null;
}): ProjectRole {
    return "member" in value ? ProjectRole.member : "admin" in value ? ProjectRole.admin : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    done: null;
} | {
    todo: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "done" in value ? TaskStatus.done : "todo" in value ? TaskStatus.todo : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): TaskPriority {
    return "low" in value ? TaskPriority.low : "high" in value ? TaskPriority.high : "medium" in value ? TaskPriority.medium : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _ProjectError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: ProjectError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ProjectError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthorized: null;
} | {
    notMember: null;
} | {
    alreadyMember: null;
} | {
    notFound: bigint;
} | {
    invalidName: null;
}): {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notMember";
    notMember: null;
} | {
    __kind__: "alreadyMember";
    alreadyMember: null;
} | {
    __kind__: "notFound";
    notFound: bigint;
} | {
    __kind__: "invalidName";
    invalidName: null;
} {
    return "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "notMember" in value ? {
        __kind__: "notMember",
        notMember: value.notMember
    } : "alreadyMember" in value ? {
        __kind__: "alreadyMember",
        alreadyMember: value.alreadyMember
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "invalidName" in value ? {
        __kind__: "invalidName",
        invalidName: value.invalidName
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectMember>): Array<ProjectMember> {
    return value.map((x)=>from_candid_ProjectMember_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectProgress>): Array<ProjectProgress> {
    return value.map((x)=>from_candid_ProjectProgress_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n26(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == TaskPriority.low ? {
        low: null
    } : value == TaskPriority.high ? {
        high: null
    } : value == TaskPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    done: null;
} | {
    todo: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.done ? {
        done: null
    } : value == TaskStatus.todo ? {
        todo: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    active: null;
} | {
    completed: null;
} | {
    archived: null;
} {
    return value == ProjectStatus.active ? {
        active: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.archived ? {
        archived: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
